services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
  
  rabbitmq:
    image: rabbitmq:4.1.3-management 
    ports: ["5672:5672", "15672:15672"]
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
  
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    depends_on: [mongo, rabbitmq]
    environment:
      MONGO_URL: ${MONGO_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      PORT: 3001
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports: ["3001:3001"]
  
  worker:
    build: ./worker
    depends_on: [mongo, rabbitmq]
    environment:
      MONGO_URL: ${MONGO_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
  web:
    build: ./web
    depends_on: [api]
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports: ["3000:3000"]
  
volumes:
  mongo_data: 
  